"""Add image and video URLs to products

Revision ID: add_product_images
Revises: 83343540558f
Create Date: 2025-01-26 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'add_product_images'
down_revision = '83343540558f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('video_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'video_urls')
    op.drop_column('products', 'image_urls')
    # ### end Alembic commands ###